# Generated by Django 3.2.15 on 2023-12-29 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativaBurla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_deteccao', models.CharField(max_length=250)),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('data_tentativa', models.DateTimeField(auto_now_add=True, verbose_name='Data da Tentativa')),
                ('informacoes_adicionais', models.TextField(blank=True, null=True, verbose_name='Informações Adicionais')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Usuário suspeito de tentar burla o sistema',
                'verbose_name_plural': 'Usuários suspeitos de tentar burla o sistema',
            },
        ),
    ]
