# Generated by Django 3.2.15 on 2023-12-29 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardiao', '0002_tentativaburla_dt_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tentativaburla',
            name='dt_register',
        ),
    ]
