# Generated by Django 4.2.24 on 2025-12-01 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True)),
                ('icone', models.CharField(help_text='Ex: fa-file-invoice, fa-balance-scale, fa-comments', max_length=50)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('dt_alteracao', models.DateField(auto_now=True)),
                ('user_inclusao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ServicoUserInclusao', to=settings.AUTH_USER_MODEL)),
                ('user_ultima_alteracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ServicoUserAlteracao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['id', 'titulo'],
            },
        ),
    ]
