# Generated by Django 4.2.27 on 2025-12-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('corpo_da_noticia', models.TextField()),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['id', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='PaginasRelacionadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Aparece ao passar o mouse', max_length=100)),
                ('imagem', models.ImageField(upload_to='paginasrelacionadas/')),
                ('link', models.URLField()),
            ],
        ),
    ]
