# Generated by Django 4.2.2 on 2023-08-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='numero',
            field=models.CharField(max_length=8, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='possui_cnpj',
            field=models.BooleanField(default=False, verbose_name='Possui CNPJ?'),
        ),
    ]
