# Generated by Django 4.2.2 on 2023-08-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_pessoa_numero_pessoa_possui_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='possui_cnpj',
            field=models.BooleanField(default=False, verbose_name='Você possui empresa?'),
        ),
    ]
