# Generated by Django 3.2.15 on 2023-12-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_alter_pessoa_possui_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='endereco',
            field=models.CharField(max_length=128, null=True, verbose_name='Endereço'),
        ),
    ]
